import random

midiInsts = [
    "0   Acoustic Grand Piano",
    "1   Bright Acoustic Piano",
    "2   Electric Grand Piano",
    "3   Honky-Tonk Piano",
    "4   Electric Piano 1",
    "5   Electric Piano 2",
    "6   Harpsichord",
    "7   Clavinet",
    "8   Celesta",
    "9   Glockenspiel",
    "10  Music Box",
    "11  Vibraphone",
    "12  Marimba",
    "13  Xylophone",
    "14  Tubular Bells",
    "15  Dulcimer",
    "16  Drawbar Organ",
    "17  Percussive Organ",
    "18  Rock Organ",
    "19  Church Organ",
    "20  Reed Organ",
    "21  Accordion",
    "22  Harmonica",
    "23  Concertina",
    "24  Nylon Acoustic Gtr",
    "25  Steel Acoustic Gtr",
    "26  Jazz Gtr",
    "27  Clean Gtr",
    "28  Muted Gtr",
    "29  Overdriven Gtr",
    "30  Distortion Gtr",
    "31  Gtr Harmonics",
    "32  Acoustic Bass",
    "33  Fingered Bass",
    "34  Picked Bass",
    "35  Fretless Bass",
    "36  Slap Bass 1",
    "37  Slap Bass 2",
    "38  Synth Bass 1",
    "39  Synth Bass 2",
    "40  Violin",
    "41  Viola",
    "42  Cello",
    "43  Contrabass",
    "44  Tremolo Strings",
    "45  Pizzicato Strings",
    "46  Orc Harp",
    "47  Timpani",
    "48  String Ensemble 1",
    "49  String Ensemble 2",
    "50  Synth Strings 1",
    "51  Synth Strings 2",
    "52  Choir Aahs",
    "53  Voice Oohs",
    "54  Synth Voice",
    "55  Orchestra Hit",
    "56  Trumpet",
    "57  Trombone",
    "58  Tuba",
    "59  Muted Trumpet",
    "60  French Horn",
    "61  Brass Section",
    "62  Synth Brass 1",
    "63  Synth Brass 2",
    "64  Soprano Sax",
    "65  Alto Sax",
    "66  Tenor Sax",
    "67  Baritone Sax",
    "68  Oboe",
    "69  English Horn",
    "70  Bassoon",
    "71  Clarinet",
    "72  Piccolo",
    "73  Flute",
    "74  Recorder",
    "75  Pan Flute",
    "76  Bottle Blow",
    "77  Shakuhachi",
    "78  Whistle",
    "79  Ocarina",
    "80  Square Lead",
    "81  Sawtooth Lead",
    "82  Calliope Lead",
    "83  Chiff Lead",
    "84  Charang Lead",
    "85  Voice Lead",
    "86  Fifths Lead",
    "87  Bass+Ld Lead",
    "88  New Age Pad",
    "89  Warm Pad",
    "90  Polysynth Pad",
    "91  Choir Pad",
    "92  Bowed Pad",
    "93  Metallic Pad",
    "94  Halo Pad",
    "95  Sweep Pad",
    "96  Rain",
    "97  Soundtrack",
    "98  Crystal",
    "99  Atmosphere",
    "100 Brightness",
    "101 Goblins",
    "102 Echoes",
    "103 Scifi",
    "104 Sitar",
    "105 Banjo",
    "106 Shamisen",
    "107 Koto",
    "108 Kalimba",
    "109 Bagpipe",
    "110 Fiddle",
    "111 Shanai",
    "112 Tinkle Bell",
    "113 Agogo",
    "114 Steel Drums",
    "115 Woodblock",
    "116 Taiko Drum",
    "117 Melodic Tom",
    "118 Synth Drum",
    "119 Reverse Cymbal",
    "120 Gtr Fret Noise",
    "121 Breath Noise",
    "122 Seashore",
    "123 Bird Tweet",
    "124 Telephone",
    "125 Helicopter",
    "126 Applause",
    "127 Gunshot"
]

midiDrumKits = [
    "0   Standard",
    "8   Room",
    "16  Power",
    "24  Electronic",
    "25  TR-808",
    "32  Jazz",
    "40  Brush",
    "48  Orchestral",
    "56  SFX"
]

pickedInsts = []

numInsts: int = input("How many instruments do you wish to have? ")
includeDrum: str = input("Do you also want a drum kit? [y/N] ")

# TODO: Add input validation and duplicate entry prevention.
for i in range(0, int(numInsts)):
    pickedInsts.append(random.choice(midiInsts))

if includeDrum == "Y".lower():
    pickedInsts.append(random.choice(midiDrumKits))

print("Your instruments are:\n")
for entry in pickedInsts:
    print(entry)

